version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-api
  
  auth-api:
    build: ./auth-api
    ports:
      - "4000:4000"

  todos-api:
    build: ./todos-api
    ports:
      - "3000:3000"

  users-api:
    build: ./users-api
    ports:
      - "8080:8080"

  log-message-processor:
    build: ./log-message-processor
    depends_on:
      - redis

  redis:
    image: "redis:alpine"